import { RouteInfo } from "./course-sidebar.metadata";

export const ROUTES: RouteInfo[] = [
	{
		path: "/dashboard",
		title: "Main Dashboard",
		icon: "ft-chevrons-left",
		class: "",
		badge: "",
		badgeClass: "",
		isExternalLink: false,
		permission: "list-campaign",
		submenu: [],
	},
	{
		path: "/campaign",
		title: "Campaign List",
		icon: "ft-chevrons-left",
		class: "",
		badge: "",
		badgeClass: "",
		isExternalLink: false,
		permission: "list-campaign",
		submenu: [],
	},
	{
		path: "/campaign-dashboard",
		title: "Campaign Dashboard",
		icon: "ft-chevrons-left",
		class: "",
		badge: "",
		badgeClass: "",
		isExternalLink: false,
		permission: "list-campaign-dashboard",
		submenu: [],
	},
	{
		path: "/course-dashboard",
		title: "Dashboard",
		icon: "ft-server",
		class: "",
		badge: "",
		badgeClass: "",
		isExternalLink: false,
		permission: "list-course-dashboard",
		submenu: [],
	},
	{
		path: "/course-user-role",
		title: "Course User Roles",
		icon: "ft-server",
		class: "",
		badge: "",
		badgeClass: "",
		isExternalLink: false,
		permission: "list-course-user-role",
		submenu: [],
	},
	{
		path: "/section",
		title: "Section",
		icon: "ft-users",
		class: "",
		badge: "",
		badgeClass: "",
		isExternalLink: false,
		permission: "list-section",
		submenu: [],
	},
	{
		path: "/lesson",
		title: "Lesson",
		icon: "ft-server",
		class: "",
		badge: "",
		badgeClass: "",
		isExternalLink: false,
		permission: "list-lesson",
		submenu: [],
	},
	{
		path: "/quiz",
		title: "Quiz",
		icon: "ft-layers",
		class: "",
		badge: "",
		badgeClass: "",
		isExternalLink: false,
		permission: "list-quiz",
		submenu: [],
	},
];
